name: CI

on:
  push:

  workflow_dispatch:
    inputs:
      job:
        description: 'The name of the manual job.'
        required: false
#         default: 'manual_job'

env:
  GITHUB_CONTEXT_01: ${{ toJson(github) }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Commands in parallel - Test01
#         run: |
#           chmod +x ./script.sh
#           ./script.sh

      - name: view the github context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

  manual_job:
    name: Manual Job
#     if: ${{ github.event.inputs.job == '' || github.event.inputs.job == 'manual_job' }}
    runs-on: ubuntu-latest
    env:
      GITHUB_CONTEXT_02: ${{ toJson(github) }}
    steps:
      - name: view the github context 01
        run: echo "$GITHUB_CONTEXT_01"

      - name: view the github context 02
        run: echo "$GITHUB_CONTEXT_02"

      - name: view the github context 03
        if: ${{ github.event.inputs.job == github.job }}
        run: echo "$GITHUB_CONTEXT_03"
        env:
          GITHUB_CONTEXT_03: ${{ toJson(github) }}
