name: CI

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Commands in parallel - Test01
#         run: |
#           chmod +x ./script.sh
#           ./script.sh

      - name: Test access secrets
        run: |
          branch=master
          echo "branch = $branch"
          
          secret_name="secrets.${branch^^}"
          echo "secret_name = $secret_name"
          
          secret_value=${{ ${!secret_name} }}
          echo "secret_value = $secret_value"
