name: CI

on: [workflow_dispatch, push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: view the github context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: sleep
        run: |
          echo "Start - $(date +"%H:%M:%S")"
          sleep 95
          echo "End - $(date +"%H:%M:%S")"

#       - name: Commands in parallel - Test01
#         run: |
#           chmod +x ./script.sh
#           ./script.sh
