name: CI

on:
  workflow_dispatch:
#   push:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout - 1
        uses: actions/checkout@v2

#       - name: Commands in parallel - Test01
#         run: |
#           chmod +x ./script.sh
#           ./script.sh

      - name: view the github context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Checkout code - 2
        uses: actions/checkout@v2
