name: CI

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Commands in parallel - Test01
#         run: |
#           chmod +x ./script.sh
#           ./script.sh

      - name: Test access secrets
        run: |
          branch=master
          echo "branch = $branch"
          
          secret_name="secrets.${branch^^}"
          echo "secret_name = $secret_name"
          
          var1_and_var1="var1 and var2"
          var01="var1"
          var02="var2"
          var_all="$var01_and_$var02"
          echo "var1_and_var1 = ${!var_all}"
