name: CI

on:
  workflow_dispatch:
#   push:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout - 1
        uses: actions/checkout@v1

#       - name: Commands in parallel - Test01
#         run: |
#           chmod +x ./script.sh
#           ./script.sh

      - name: view the github context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: view refs
        run: |
          echo "====================================== pr ref ======================================"
          echo "github.ref = ${{ github.ref }}"
          echo "github.sha = ${{ github.sha }}"
          echo "===================================== base ref ====================================="
          echo "github.event.pull_request.base.ref = ${{ github.event.pull_request.base.ref }}"
          echo "github.event.pull_request.base.sha = ${{ github.event.pull_request.base.sha }}"
          echo "===================================== head ref ====================================="
          echo "github.event.pull_request.head.ref = ${{ github.event.pull_request.head.ref }}"
          echo "github.event.pull_request.head.sha = ${{ github.event.pull_request.head.sha }}"

      - name: Checkout code - 2
        uses: actions/checkout@v1
