name: CI

on: [workflow_dispatch, push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: view the github context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: view test.txt
        run: cat test.txt

      - name: view test02.txt
        run: cat test02.txt

      - name: view test03.txt
        run: cat test03.txt

#       - name: Commands in parallel - Test01
#         run: |
#           chmod +x ./script.sh
#           ./script.sh
