name: CI

on:
  pull_request:
    paths: 
      - 'Test_Folder/**'

jobs:
  workflow_info:
    name: Information about the workflow run
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    runs-on: [ubuntu-latest]
    steps:
      - name: Show Information
        run: |
          echo "This workflow run is triggered by ${{ github.event_name }} ."
          echo "***********************************************************************************"
          echo "$GITHUB_CONTEXT"
          echo "***********************************************************************************"
    
