name: CI

on:
  push:
  pull_request:
    types: [labeled]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Commands in parallel - Test01
#         run: |
#           chmod +x ./script.sh
#           ./script.sh

      - name: view the github context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: remove labels
        if: ${{ contains(github.event.pull_request.labels.*.name, 'ci-check/vagrant-setup') }}
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.github_token }}
          labels: ci-check/vagrant-setup
