name: CI

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Commands in parallel - Test01
#         run: |
#           chmod +x ./script.sh
#           ./script.sh

      - name: Check dir
        run: echo $PWD

      - name: Test docker container action
        uses: TestCustomActionsRML/hello-world-docker-action@master

      - name: Check file
        run: |
          ls
          cat test.txt
