name: Pytest

on: 
  push:
    branches: 
      - master

jobs:
  run_python_tests:
    name: Run Python Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: GitHub Action for pytest
        uses: cclauss/GitHub-Action-for-pytest@master
        with:
          args: pytest -h
