name: Python Tests

on: 
  push:
    branches: 
      - master

jobs:
  run_python_tests:
    name: Run Python Tests
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
