name: Test

on: push

env:
  RUN_START: false

jobs:
  job_one:
    name: Job One
    runs-on: ubuntu-latest
    steps:
      - name: Run Job One
        run: |
          echo "Run Job One"
          echo "::set-output name=RUN_START::true"

  job_two:
    needs: [job_one]
    name: Job Two
    runs-on: ubuntu-latest
    steps:
      - name: Run Job Two
        run: |
          echo "Run Job Two"

  job_three:
    needs: [job_one, job_two]
    name: Job Three
    runs-on: ubuntu-latest
    steps:
      - name: Run Job Three
        run: |
          echo "Run Job Three"
          echo $RUN_START
