name: Test

on: push

jobs:
  job1:
    name: Job One
    runs-on: ubuntu-latest
    steps:
      - name: View the github context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Get name
        run: |
          name=$(GITHUB_REF##/*)
          echo $name
