name: Test

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python environment
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'

      - name: Check shebang (#!) maximum line length
        shell: bash
        run: |
          grep BINPRM_BUF_SIZE /usr/include/linux/binfmts.h
