name: Test

on: push

jobs:
  job1:
    name: Job One
    runs-on: windows-latest
    steps:
      - name: View the github context
        shell: bash
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Extract ref name
        shell: bash
        run: echo "::set-env name=REF_NAME::${GITHUB_REF##*/}"

      - name: show ref name
        shell: pwsh
        run: echo "The ref name is ${{ env.REF_NAME }}"
