name: Test

on: push

jobs:
  job1:
    name: Job One
    runs-on: windows-latest
    steps:
      - name: View the github context
        shell: bash
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Get name
        run: echo "the name is ${GITHUB_REF##*/}"
